import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <div className="flex gap-6 p-4 bg-gray-100 border-b">
          <Link href="/" className="text-blue-600 hover:underline">Home</Link>
          <Link href="/about" className="text-blue-600 hover:underline">About</Link>
          <Link href="/contact" className="text-blue-600 hover:underline">Contact</Link>
        </div>
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
